# Generated by Django 5.2.5 on 2025-08-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=20)),
                ('file_extension', models.CharField(max_length=20)),
                ('format_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Formato de Imagem',
                'verbose_name_plural': 'Formatos de Imagem',
            },
        ),
    ]
