# Generated by Django 5.2.5 on 2025-08-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageformat',
            name='format_name',
            field=models.CharField(max_length=60),
        ),
    ]
