# Generated by Django 5.2.5 on 2025-08-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_imageformat_format_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageformat',
            name='file_extension',
            field=models.CharField(max_length=50),
        ),
    ]
